language: node_js
node_js:
  - lts/*
  - node
before_install:
  - npm install -g codecov
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
  - codecov
