service: images

custom:
  stage: "${opt:stage, self:provider.stage}"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  versionFunctions: false
  environment: ${file(env.yml):${self:custom.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.env.BUCKET_NAME}/*"

package:
  include:
    - dist/**
    - node_modules/**
  exclude:
    - src/**
    - env.yml

functions:
  update:
    handler: dist/handler.handler
    events:
      - http:
          path: images
          method: get
