service: image-master

custom:
  stage: "${opt:stage, self:provider.stage}"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  versionFunctions: false
  environment: ${file(env.yml):${self:custom.stage}}

package:
  include:
    - dist/**
    - node_modules/**
  exclude:
    - src/**
    - env.yml

functions:
  update:
    handler: dist/handler.update
    events:
      - sns: ${self:custom.env.EH_SNS_IMAGE}
