service: images

custom:
  stage: "${opt:stage, self:provider.stage}"
  env: ${file(env.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  versionFunctions: false
  environment: ${self:custom.env}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.env.BUCKET_NAME}/*"

package:
  exclude:
    - test/**
    - env.yml
    - invoke.js
    - package-lock.json

functions:
  update:
    handler: handler.handler
    events:
      - http:
          path: images
          method: get
