service: show-updater

custom:
  stage: '${opt:stage, self:provider.stage}'
  env: ${file(env.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  timeout: 25
  versionFunctions: false
  environment: ${self:custom.env}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "arn:aws:lambda:us-east-1:*:function:*"

package:
  include:
    - dist/**
    - node_modules/**
  exclude:
    - src/**
    - env.yml
    - .git/**
    - .vscode/**

functions:
  update:
    handler: red-keep/handler.update
    events:
      - sns: ${self:custom.env.EH_SNS_UPDATE_SHOW}
  add:
    handler: red-keep/handler.add
  update2:
    handler: dragonstone/handler.update
    events:
      - sns: ${self:custom.env.SNS_UPDATE_SHOW_TOPIC}
  add2:
    handler: dragonstone/handler.add
