service: show-updater

custom:
  stage: '${opt:stage, self:provider.stage}'
  env: ${file(env.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  timeout: 25
  versionFunctions: false
  environment: ${self:custom.env}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: 'arn:aws:lambda:us-east-1:*:function:*'

package:
  include:
    - node_modules/**
  exclude:
    - env.yml

functions:
  update:
    handler: handler.update
    events:
      - sns: ${self:custom.env.EH_SNS_UPDATE_SHOW}
  add:
    handler: handler.add
