service: episodehunter-show-update

custom:
  stage: "${opt:stage, self:provider.stage}"
  env: ${file(env.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  timeout: 25
  versionFunctions: false
  environment: ${self:custom.env}

package:
  include:
    - dist/**
    - node_modules/**
  exclude:
    - src/**
    - env.yml
    - .git/**
    - .vscode/**

functions:
  update:
    handler: dist/handler.update
    events:
      - sns: ${self:custom.env.EH_SNS_UPDATE_SHOW}
