service: scheduler

custom:
  stage: '${opt:stage, self:provider.stage}'
  env: ${file(env.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  versionFunctions: false
  environment: ${self:custom.env}
  timeout: 20
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource:
        - ${self:custom.env.EH_SNS_UPDATE_SHOW}
        - ${self:custom.env.SNS_UPDATE_SHOW_TOPIC}

package:
  include:
    - node_modules/**
    - src/**
  exclude:
    - __mocks__
    - env.yml

functions:
  thetvdb:
    handler: src/show-updater-handler.update
    events:
      - schedule: rate(2 hours)
  showupdater:
    handler: src/dragonstone-show-updater-handler.update
    events:
      - schedule: rate(2 hours)
  titlesupdater:
    handler: src/show-updater-handler.update
    events:
      - schedule: rate(24 hours)
