service: scheduler

custom:
  stage: '${opt:stage, self:provider.stage}'
  env: ${file(env.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  versionFunctions: false
  environment: ${self:custom.env}
  timeout: 20
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource:
        - ${self:custom.env.EH_SNS_UPDATE_SHOW}

package:
  include:
    - node_modules/**
  exclude:
    - env.yml

functions:
  showupdater:
    handler: handler.updateOldestShows
    events:
      - schedule: rate(15 minutes)
