service: scheduler

custom:
  stage: '${opt:stage, self:provider.stage}'
  env: ${file(env.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  versionFunctions: false
  environment: ${self:custom.env}
  timeout: 20
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource:
        - ${self:custom.env.EH_SNS_UPDATE_SHOW}

package:
  include:
    - dist/**
    - node_modules/**
  exclude:
    - src/**
    - env.yml
    - .git/**
    - .vscode/**

functions:
  thetvdb:
    handler: dist/show-updater-handler.update
    events:
      - schedule: rate(2 hours)
  titlesupdater:
    handler: dist/show-updater-handler.update
    events:
      - schedule: rate(24 hours)
